[tool.poetry]
name = "lpfun"
version = "0.2"
description = " A package for fast multivariate interpolation and differentiation. "
authors = ["Phil-Alexander Hofmann"]
license = "MIT"
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.9,<4.0"
numba = ">=0.60,<0.61"
numpy = ">=1.26,<3.0"
scipy = ">=1.13,<2.0"


[tool.poetry.group.dev.dependencies]
pytest = ">=8.0,<9.0"
black = ">=24.0,<25.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
